<?php

namespace PHPMaker2022\school;

// Menu Language
if ($Language && function_exists(PROJECT_NAMESPACE . "Config") && $Language->LanguageFolder == Config("LANGUAGE_FOLDER")) {
    $MenuRelativePath = "";
    $MenuLanguage = &$Language;
} else { // Compat reports
    $LANGUAGE_FOLDER = "../lang/";
    $MenuRelativePath = "../";
    $MenuLanguage = Container("language");
}

// Navbar menu
$topMenu = new Menu("navbar", true, true);
$topMenu->addMenuItem(3, "mi_school_member", $MenuLanguage->MenuPhrase("3", "MenuText"), $MenuRelativePath . "SchoolMemberList?cmd=resetall", -1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_member'), false, false, "fa-user-cog", "", true, false);
$topMenu->addMenuItem(182, "mci_Financial", $MenuLanguage->MenuPhrase("182", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-funnel-dollar", "", true, false);
$topMenu->addMenuItem(138, "mi_fin_accountsreceivable", $MenuLanguage->MenuPhrase("138", "MenuText"), $MenuRelativePath . "FinAccountsreceivableList", 182, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_accountsreceivable'), false, false, "", "", true, false);
$topMenu->addMenuItem(133, "mi_fin_accountspayable", $MenuLanguage->MenuPhrase("133", "MenuText"), $MenuRelativePath . "FinAccountspayableList", 182, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_accountspayable'), false, false, "", "", true, false);
$topMenu->addMenuItem(183, "mci_Auxiliary", $MenuLanguage->MenuPhrase("183", "MenuText"), "", 182, "", IsLoggedIn(), false, true, "", "", true, false);
$topMenu->addMenuItem(134, "mi_fin_type", $MenuLanguage->MenuPhrase("134", "MenuText"), $MenuRelativePath . "FinTypeList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_type'), false, false, "", "", true, false);
$topMenu->addMenuItem(187, "mi_fin_discount", $MenuLanguage->MenuPhrase("187", "MenuText"), $MenuRelativePath . "FinDiscountList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_discount'), false, false, "", "", true, false);
$topMenu->addMenuItem(135, "mi_fin_department", $MenuLanguage->MenuPhrase("135", "MenuText"), $MenuRelativePath . "FinDepartmentList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_department'), false, false, "", "", true, false);
$topMenu->addMenuItem(188, "mi_fin_paymentmethod", $MenuLanguage->MenuPhrase("188", "MenuText"), $MenuRelativePath . "FinPaymentmethodList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_paymentmethod'), false, false, "", "", true, false);
$topMenu->addMenuItem(136, "mi_fin_creditors", $MenuLanguage->MenuPhrase("136", "MenuText"), $MenuRelativePath . "FinCreditorsList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_creditors'), false, false, "", "", true, false);
$topMenu->addMenuItem(137, "mi_fin_costcenter", $MenuLanguage->MenuPhrase("137", "MenuText"), $MenuRelativePath . "FinCostcenterList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_costcenter'), false, false, "", "", true, false);
$topMenu->addMenuItem(184, "mi_fin_checkingaccount", $MenuLanguage->MenuPhrase("184", "MenuText"), $MenuRelativePath . "FinCheckingaccountList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_checkingaccount'), false, false, "", "", true, false);
$topMenu->addMenuItem(21, "mci_Gerenciamento_da_escola", $MenuLanguage->MenuPhrase("21", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-school", "", true, false);
$topMenu->addMenuItem(4, "mi_school_modality", $MenuLanguage->MenuPhrase("4", "MenuText"), $MenuRelativePath . "SchoolModalityList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_modality'), false, false, "", "", true, false);
$topMenu->addMenuItem(2, "mi_school_program", $MenuLanguage->MenuPhrase("2", "MenuText"), $MenuRelativePath . "SchoolProgramList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_program'), false, false, "", "", true, false);
$topMenu->addMenuItem(5, "mi_school_class", $MenuLanguage->MenuPhrase("5", "MenuText"), $MenuRelativePath . "SchoolClassList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_class'), false, false, "", "", true, false);
$topMenu->addMenuItem(192, "mi_fin_employee", $MenuLanguage->MenuPhrase("192", "MenuText"), $MenuRelativePath . "FinEmployeeList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_employee'), false, false, "", "", true, false);
echo $topMenu->toScript();

// Sidebar menu
$sideMenu = new Menu("menu", true, false);
$sideMenu->addMenuItem(201, "mi_view_news", $MenuLanguage->MenuPhrase("201", "MenuText"), $MenuRelativePath . "ViewNewsList", -1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}view_news'), false, false, "fa-newspaper", "", false, true);
$sideMenu->addMenuItem(193, "mi_conf_news", $MenuLanguage->MenuPhrase("193", "MenuText"), $MenuRelativePath . "ConfNewsList", 201, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_news'), false, false, "", "", false, true);
$sideMenu->addMenuItem(3, "mi_school_member", $MenuLanguage->MenuPhrase("3", "MenuText"), $MenuRelativePath . "SchoolMemberList?cmd=resetall", -1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_member'), false, false, "fa-user-cog", "", true, true);
$sideMenu->addMenuItem(182, "mci_Financial", $MenuLanguage->MenuPhrase("182", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-funnel-dollar", "", true, true);
$sideMenu->addMenuItem(138, "mi_fin_accountsreceivable", $MenuLanguage->MenuPhrase("138", "MenuText"), $MenuRelativePath . "FinAccountsreceivableList", 182, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_accountsreceivable'), false, false, "", "", true, true);
$sideMenu->addMenuItem(133, "mi_fin_accountspayable", $MenuLanguage->MenuPhrase("133", "MenuText"), $MenuRelativePath . "FinAccountspayableList", 182, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_accountspayable'), false, false, "", "", true, true);
$sideMenu->addMenuItem(183, "mci_Auxiliary", $MenuLanguage->MenuPhrase("183", "MenuText"), "", 182, "", IsLoggedIn(), false, true, "", "", true, true);
$sideMenu->addMenuItem(134, "mi_fin_type", $MenuLanguage->MenuPhrase("134", "MenuText"), $MenuRelativePath . "FinTypeList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_type'), false, false, "", "", true, true);
$sideMenu->addMenuItem(187, "mi_fin_discount", $MenuLanguage->MenuPhrase("187", "MenuText"), $MenuRelativePath . "FinDiscountList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_discount'), false, false, "", "", true, true);
$sideMenu->addMenuItem(135, "mi_fin_department", $MenuLanguage->MenuPhrase("135", "MenuText"), $MenuRelativePath . "FinDepartmentList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_department'), false, false, "", "", true, true);
$sideMenu->addMenuItem(188, "mi_fin_paymentmethod", $MenuLanguage->MenuPhrase("188", "MenuText"), $MenuRelativePath . "FinPaymentmethodList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_paymentmethod'), false, false, "", "", true, true);
$sideMenu->addMenuItem(136, "mi_fin_creditors", $MenuLanguage->MenuPhrase("136", "MenuText"), $MenuRelativePath . "FinCreditorsList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_creditors'), false, false, "", "", true, true);
$sideMenu->addMenuItem(137, "mi_fin_costcenter", $MenuLanguage->MenuPhrase("137", "MenuText"), $MenuRelativePath . "FinCostcenterList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_costcenter'), false, false, "", "", true, true);
$sideMenu->addMenuItem(184, "mi_fin_checkingaccount", $MenuLanguage->MenuPhrase("184", "MenuText"), $MenuRelativePath . "FinCheckingaccountList", 183, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_checkingaccount'), false, false, "", "", true, true);
$sideMenu->addMenuItem(21, "mci_Gerenciamento_da_escola", $MenuLanguage->MenuPhrase("21", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-school", "", true, true);
$sideMenu->addMenuItem(4, "mi_school_modality", $MenuLanguage->MenuPhrase("4", "MenuText"), $MenuRelativePath . "SchoolModalityList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_modality'), false, false, "", "", true, true);
$sideMenu->addMenuItem(2, "mi_school_program", $MenuLanguage->MenuPhrase("2", "MenuText"), $MenuRelativePath . "SchoolProgramList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_program'), false, false, "", "", true, true);
$sideMenu->addMenuItem(5, "mi_school_class", $MenuLanguage->MenuPhrase("5", "MenuText"), $MenuRelativePath . "SchoolClassList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_class'), false, false, "", "", true, true);
$sideMenu->addMenuItem(192, "mi_fin_employee", $MenuLanguage->MenuPhrase("192", "MenuText"), $MenuRelativePath . "FinEmployeeList", 21, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fin_employee'), false, false, "", "", true, true);
$sideMenu->addMenuItem(22, "mci_Geral", $MenuLanguage->MenuPhrase("22", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-cogs", "", false, true);
$sideMenu->addMenuItem(1, "mi_school_users", $MenuLanguage->MenuPhrase("1", "MenuText"), $MenuRelativePath . "SchoolUsersList?cmd=resetall", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}school_users'), false, false, "fa-users", "", false, true);
$sideMenu->addMenuItem(8, "mi_userlevelpermissions", $MenuLanguage->MenuPhrase("8", "MenuText"), $MenuRelativePath . "UserlevelpermissionsList", 1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}userlevelpermissions'), false, false, "fa-user-tag", "", false, true);
$sideMenu->addMenuItem(9, "mi_userlevels", $MenuLanguage->MenuPhrase("9", "MenuText"), $MenuRelativePath . "UserlevelsList", 1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}userlevels'), false, false, "fa-user-shield", "", false, true);
$sideMenu->addMenuItem(200, "mi_conf_marketingsource", $MenuLanguage->MenuPhrase("200", "MenuText"), $MenuRelativePath . "ConfMarketingsourceList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_marketingsource'), false, false, "fa-comments", "", false, true);
$sideMenu->addMenuItem(11, "mi_fed_federation", $MenuLanguage->MenuPhrase("11", "MenuText"), $MenuRelativePath . "FedFederationList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_federation'), false, false, "fa-university", "", false, true);
$sideMenu->addMenuItem(86, "mci_Region", $MenuLanguage->MenuPhrase("86", "MenuText"), "", 22, "", IsLoggedIn(), false, true, "fa-map", "", false, true);
$sideMenu->addMenuItem(13, "mi_conf_country", $MenuLanguage->MenuPhrase("13", "MenuText"), $MenuRelativePath . "ConfCountryList", 86, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_country'), false, false, "fa-globe-americas", "", false, true);
$sideMenu->addMenuItem(20, "mi_conf_uf", $MenuLanguage->MenuPhrase("20", "MenuText"), $MenuRelativePath . "ConfUfList", 86, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_uf'), false, false, "fa-map-marked-alt", "", false, true);
$sideMenu->addMenuItem(12, "mi_conf_city", $MenuLanguage->MenuPhrase("12", "MenuText"), $MenuRelativePath . "ConfCityList", 86, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_city'), false, false, "fa-map-marker-alt", "", false, true);
$sideMenu->addMenuItem(203, "mi_conf_membertype", $MenuLanguage->MenuPhrase("203", "MenuText"), $MenuRelativePath . "ConfMembertypeList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_membertype'), false, false, "fa-tags", "", false, true);
$sideMenu->addMenuItem(14, "mi_conf_scholarity", $MenuLanguage->MenuPhrase("14", "MenuText"), $MenuRelativePath . "ConfScholarityList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_scholarity'), false, false, "fa-user-graduate", "", false, true);
$sideMenu->addMenuItem(15, "mi_conf_schooltype", $MenuLanguage->MenuPhrase("15", "MenuText"), $MenuRelativePath . "ConfSchooltypeList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_schooltype'), false, false, "fa-school", "", false, true);
$sideMenu->addMenuItem(23, "mi_conf_memberstatus", $MenuLanguage->MenuPhrase("23", "MenuText"), $MenuRelativePath . "ConfMemberstatusList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_memberstatus'), false, false, "fa-star", "", false, true);
$sideMenu->addMenuItem(10, "mi_fed_applicationschool", $MenuLanguage->MenuPhrase("10", "MenuText"), $MenuRelativePath . "FedApplicationschoolList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_applicationschool'), false, false, "fa-laptop-house", "", false, true);
$sideMenu->addMenuItem(199, "mi_fed_school", $MenuLanguage->MenuPhrase("199", "MenuText"), $MenuRelativePath . "FedSchoolList?cmd=resetall", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_school'), false, false, "fa-school", "", false, true);
$sideMenu->addMenuItem(197, "mi_fed_martialarts", $MenuLanguage->MenuPhrase("197", "MenuText"), $MenuRelativePath . "FedMartialartsList", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_martialarts'), false, false, "fa-rocket", "", false, true);
$sideMenu->addMenuItem(196, "mi_fed_rank", $MenuLanguage->MenuPhrase("196", "MenuText"), $MenuRelativePath . "FedRankList?cmd=resetall", 22, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_rank'), false, false, "fa-sort-amount-up-alt", "", false, true);
$sideMenu->addMenuItem(54, "mci_Marketing_and_Media", $MenuLanguage->MenuPhrase("54", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-mail-bulk", "", false, true);
$sideMenu->addMenuItem(28, "mi_fed_files", $MenuLanguage->MenuPhrase("28", "MenuText"), $MenuRelativePath . "FedFilesList", 54, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_files'), false, false, "fa-folder-open", "", false, true);
$sideMenu->addMenuItem(29, "mi_fed_filescategory", $MenuLanguage->MenuPhrase("29", "MenuText"), $MenuRelativePath . "FedFilescategoryList", 28, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_filescategory'), false, false, "fa-archive", "", false, true);
$sideMenu->addMenuItem(30, "mi_fed_filestype", $MenuLanguage->MenuPhrase("30", "MenuText"), $MenuRelativePath . "FedFilestypeList", 28, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_filestype'), false, false, "fa-folder-plus", "", false, true);
$sideMenu->addMenuItem(89, "mi_fed_video", $MenuLanguage->MenuPhrase("89", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=resetall", 54, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_video'), false, false, "fa-video", "", false, true);
$sideMenu->addMenuItem(87, "mi_fed_videosection", $MenuLanguage->MenuPhrase("87", "MenuText"), $MenuRelativePath . "FedVideosectionList", 89, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_videosection'), false, false, "fa-folder-plus", "", false, true);
$sideMenu->addMenuItem(88, "mi_fed_videosubsection", $MenuLanguage->MenuPhrase("88", "MenuText"), $MenuRelativePath . "FedVideosubsectionList?cmd=resetall", 89, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_videosubsection'), false, false, "fa-folder-plus", "", false, true);
$sideMenu->addMenuItem(128, "mci_Testing", $MenuLanguage->MenuPhrase("128", "MenuText"), "", -1, "", IsLoggedIn(), false, true, "fa-calendar-check", "", false, true);
$sideMenu->addMenuItem(131, "mi_tes_test", $MenuLanguage->MenuPhrase("131", "MenuText"), $MenuRelativePath . "TesTestList", 128, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}tes_test'), false, false, "fa-sort-amount-up-alt", "", false, true);
$sideMenu->addMenuItem(278, "mci_Manage_Tests", $MenuLanguage->MenuPhrase("278", "MenuText"), "", 128, "", true, false, true, "fa-cogs", "", false, true);
$sideMenu->addMenuItem(90, "mi_conf_testestatus", $MenuLanguage->MenuPhrase("90", "MenuText"), $MenuRelativePath . "ConfTestestatusList", 278, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_testestatus'), false, false, "fa-check", "", false, true);
$sideMenu->addMenuItem(130, "mi_tes_resultamount", $MenuLanguage->MenuPhrase("130", "MenuText"), $MenuRelativePath . "TesResultamountList", 278, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}tes_resultamount'), false, false, "fa-envelope-open-text", "", false, true);
$sideMenu->addMenuItem(132, "mi_tes_test_judge", $MenuLanguage->MenuPhrase("132", "MenuText"), $MenuRelativePath . "TesTestJudgeList", 278, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}tes_test_judge'), false, false, "fa-address-book", "", false, true);
$sideMenu->addMenuItem(91, "mi_tes_aproved", $MenuLanguage->MenuPhrase("91", "MenuText"), $MenuRelativePath . "TesAprovedList", 278, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}tes_aproved'), false, false, "fa-check-square", "", false, true);
$sideMenu->addMenuItem(16, "mi_conf_testtype", $MenuLanguage->MenuPhrase("16", "MenuText"), $MenuRelativePath . "ConfTesttypeList", 278, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}conf_testtype'), false, false, "fa-tags", "", false, true);
$sideMenu->addMenuItem(205, "mi_tes_certificate", $MenuLanguage->MenuPhrase("205", "MenuText"), $MenuRelativePath . "TesCertificateList", 278, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}tes_certificate'), false, false, "fa-envelope-open-text", "", false, true);
$sideMenu->addMenuItem(194, "mi_fed_licenseschool", $MenuLanguage->MenuPhrase("194", "MenuText"), $MenuRelativePath . "FedLicenseschoolList?cmd=resetall", -1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}fed_licenseschool'), false, false, "fa-file-invoice-dollar", "", false, true);
$sideMenu->addMenuItem(7, "mi_audittrail", $MenuLanguage->MenuPhrase("7", "MenuText"), $MenuRelativePath . "AudittrailList", -1, "", AllowListMenu('{C78C2A6C-FD4D-4227-8B14-C5BA34014477}audittrail'), false, false, "fa-user-secret", "", false, true);
$sideMenu->addMenuItem(292, "mci_Curriculum", $MenuLanguage->MenuPhrase("292", "MenuText"), "", -1, "", true, false, true, "fa-pen-to-square", "", false, true);
$sideMenu->addMenuItem(293, "mci_White_Belt", $MenuLanguage->MenuPhrase("293", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=1&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(294, "mci_Orange_Belt", $MenuLanguage->MenuPhrase("294", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=2&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(295, "mci_Yellow_Belt", $MenuLanguage->MenuPhrase("295", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=3&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(296, "mci_Camo_Belt", $MenuLanguage->MenuPhrase("296", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=4&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(297, "mci_Green_Belt", $MenuLanguage->MenuPhrase("297", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=5&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(298, "mci_Purple_Belt", $MenuLanguage->MenuPhrase("298", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=6&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(299, "mci_Blue_Belt", $MenuLanguage->MenuPhrase("299", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=7&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(300, "mci_Brown_Belt", $MenuLanguage->MenuPhrase("300", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=8&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(301, "mci_Red_Belt", $MenuLanguage->MenuPhrase("301", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=9&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(302, "mci_1_Degree_BB", $MenuLanguage->MenuPhrase("302", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=11&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
$sideMenu->addMenuItem(303, "mci_2_Degree_BB", $MenuLanguage->MenuPhrase("303", "MenuText"), $MenuRelativePath . "FedVideoList?cmd=search&t=fed_video&z_section=%3D&x_section=1&z_subsection=%3D&x_subsection=16&psearch=&psearchtype=AND", 292, "", true, false, true, "", "", false, true);
echo $sideMenu->toScript();
